version: "3.3"
services:
  rahoot:
    image: ghcr.io/yourGithubName/rahoot-dockerised
    restart: always
    networks:
      - private
  reverse-proxy:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/localUnixUser/nginx:/etc/nginx/conf.d
      - /home/localUnixUser/certs/:/etc/ssl/
    networks:
     - public
     - private
  
networks:
   private:
   public:
  
